### ISSUE TITLE
Image decoding?

### ISSUE THREAD

**Issue by TooTallNate** [pkrumins/node-image#1]
Is there any support for image decoding (of any image format I guess)?

My use case is I have a raw JPG file read into a Buffer (using `fs` to read the file from the filesystem).
I would like to resize this image before sending it to the client via HTTP.

I would first have to decode the JPG file into a RGB buffer, right? Then use the `encode` method to resize?

Or is there some better way of doing this? Thanks in advance!

**Comment by pkrumins** [comment]
There is no support for decoding and there isn't any planned.

The easiest thing you can do is the following:
1. write your buffer to file
2. call process.spawn(...) to call some program that resizes the image (like imagemagick)
3. read it back in.

**Comment by TooTallNate** [comment]
Ok, that's kinda what I figured. Bummer...

**Comment by pkrumins** [comment]
That's not too bad actually!

If you really want node-image to do it, you'd have to hack it in node-jpeg. You'd need to use the decoding interface for jpeg images, so yeah, it would take a jpeg, convert it to RGB, and then feed it back to the existing RGB->jpeg encoder with some parameters to scale it down.

**Comment by TooTallNate** [comment]
Well ideally each of the `node-jpeg`, `node-gif`, and `node-png` modules should expose a `decode` function. I think doing format conversions with these libs would be a killer feature! And doing everything inside Node just feels clean, child processes don't...

I might try to fork and implement them myself, but I never done anything in c++ so I'm not sure how successful I'm gonna be. But since it's just a matter of adding a bit of glue from the libjpeg decoding to V8, maybe it won't be too bad. Do you know of any good examples of decoding a JPG using libjpeg?

**Comment by pkrumins** [comment]
Yeah, see example.c in libjpeg. I used that to figure out how to do encoding, and it also contains an example for decoding.
