### ISSUE TITLE
Cannot install on node 0.4.8

### ISSUE THREAD

**Issue by BrazilianJoe** [pkrumins/node-image#2]
I am using Xcode 4, having previously uninstalled Xcode 3.2. I don't know if it's merely a header path issue, but I felt it was worth mentioning.

npm info install jpeg@1.0.1
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /usr/local/lib/node 
Checking for node prefix                 : ok /usr/local/Cellar/node/0.4.8 
Checking for library jpeg                : yes 
'configure' finished successfully (0.348s)
Waf: Entering directory `/usr/local/lib/node/.npm/jpeg/1.0.1/package/build'
[1/7] cxx: src/common.cpp -> build/default/src/common_1.o
[2/7] cxx: src/jpeg_encoder.cpp -> build/default/src/jpeg_encoder_1.o
[3/7] cxx: src/jpeg.cpp -> build/default/src/jpeg_1.o
[4/7] cxx: src/fixed_jpeg_stack.cpp -> build/default/src/fixed_jpeg_stack_1.o
../src/jpeg.cpp: In constructor ‘Jpeg::Jpeg(node::Buffer*, int, int, buffer_type)’:
../src/jpeg.cpp:28: error: ‘class node::Buffer’ has no member named ‘data’
../src/jpeg.cpp: In member function ‘v8::Handle<v8::Value> Jpeg::JpegEncodeSync()’:
../src/jpeg.cpp:44: error: ‘class node::Buffer’ has no member named ‘data’
../src/jpeg.cpp: In static member function ‘static int Jpeg::EIO_JpegEncodeAfter(eio_req*)’:
../src/jpeg.cpp:180: error: ‘class node::Buffer’ has no member named ‘data’
../src/fixed_jpeg_stack.cpp: In member function ‘v8::Handle<v8::Value> FixedJpegStack::JpegEncodeSync()’:
../src/fixed_jpeg_stack.cpp:45: error: ‘class node::Buffer’ has no member named ‘data’
../src/fixed_jpeg_stack.cpp: In static member function ‘static v8::Handle<v8::Value> FixedJpegStack::Push(const v8::Arguments&)’:
../src/fixed_jpeg_stack.cpp:220: error: ‘class node::Buffer’ has no member named ‘data’
../src/fixed_jpeg_stack.cpp: In static member function ‘static int FixedJpegStack::EIO_JpegEncodeAfter(eio_req*)’:
../src/fixed_jpeg_stack.cpp:291: error: ‘class node::Buffer’ has no member named ‘data’
Waf: Leaving directory`/usr/local/lib/node/.npm/jpeg/1.0.1/package/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx jpeg.cpp -> jpeg_1.o}
 -> task failed (err #1): 
    {task: cxx fixed_jpeg_stack.cpp -> fixed_jpeg_stack_1.o}
npm info jpeg@1.0.1 Failed to exec install script
npm ERR! install failed Error: jpeg@1.0.1 install: `node-waf configure build`
npm ERR! install failed `sh "-c" "node-waf configure build"` failed with 1
npm ERR! install failed     at ChildProcess.<anonymous> (/usr/local/lib/node/.npm/npm/0.3.18/package/lib/utils/exec.js:49:20)
npm ERR! install failed     at ChildProcess.emit (events.js:67:17)
npm ERR! install failed     at ChildProcess.onexit (child_process.js:192:12)
npm info install failed rollback
npm info uninstall [ 'image@1.0.1',
npm info uninstall   'png@2.0.0',
npm info uninstall   'jpeg@1.0.1',
npm info uninstall   'gif@2.0.0' ]
npm info preuninstall image@1.0.1
npm info preuninstall png@2.0.0
npm info preuninstall jpeg@1.0.1
npm info preuninstall gif@2.0.0
npm info uninstall image@1.0.1
npm info uninstall png@2.0.0
npm info uninstall jpeg@1.0.1
npm info uninstall gif@2.0.0
npm info auto-deactive not symlink
npm info auto-deactive not symlink
npm info postuninstall png@2.0.0
npm info postuninstall jpeg@1.0.1
npm info predeactivate image@1.0.1
npm info predeactivate gif@2.0.0
npm info deactivate image@1.0.1
npm info deactivate gif@2.0.0
npm info postdeactivate image@1.0.1
npm info postdeactivate gif@2.0.0
npm info postuninstall gif@2.0.0
npm info postuninstall image@1.0.1
npm info uninstall image@1.0.1 complete
npm info uninstall png@2.0.0 complete
npm info uninstall jpeg@1.0.1 complete
npm info uninstall gif@2.0.0 complete
npm info install failed rolled back
npm ERR! Error: jpeg@1.0.1 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR!     at ChildProcess.<anonymous> (/usr/local/lib/node/.npm/npm/0.3.18/package/lib/utils/exec.js:49:20)
npm ERR!     at ChildProcess.emit (events.js:67:17)
npm ERR!     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! 
npm ERR! Failed at the jpeg@1.0.1 install script.
npm ERR! This is most likely a problem with the jpeg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls jpeg
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 11.0.0
npm ERR! argv { remain: 
npm ERR! argv    [ 'image',
npm ERR! argv      'png@_',
npm ERR! argv      'jpeg@_',
npm ERR! argv      'gif@*' ],
npm ERR! argv   cooked: [ 'install', 'image' ],
npm ERR! argv   original: [ 'install', 'image' ] }
npm not ok

**Comment by pkrumins** [comment]
Hi. Node-jpeg and node-gif have not been ported to node-0.4.x, therefore this module doesn't work. I don't have any timeline for fixing these modules as I don't need them myself currently. I'd gladly accept a patch that makes them work with node 0.4.

**Comment by BrazilianJoe** [comment]
Well I am just looking for image support to try to port evercookies to nodes. I tried node-png first but it is also failing, that's why I tried this other package of yours. I guess I will concentrate my efforts in node-png, but I am not well-versed in the intricacies of node/npm building, don't know if I can help much. 

I'll see what I can do, and appreciate you good-will on this matter.
